config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root'pages#home'
  get 'pages/about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar is-black" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="https://bulma.io">
      <img src="https://cdn.discordapp.com/attachments/753405887032328314/810952374372794418/FoxLogo.png" >
    </a>

    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      
        <%=link_to "Inicio", root_path, class:"navbar-item" %>
        <%=link_to "Acerca de", pages_about_path, class:"navbar-item" %>

      <div class="navbar-item has-dropdown is-hoverable">
            <a class="navbar-link">
            Más
            </a>

            <div class="navbar-dropdown">
            <a class="navbar-item" href="https://github.com/MrFoxxz/App_3" target="_blank">
                Github
            </a>
            <a class="navbar-item">
                Jobs
            </a>
            <a class="navbar-item">
                Contacto
            </a>
            <hr class="navbar-divider">
            <a class="navbar-item">
                Report an issue
            </a>
            </div>
      </div>
    </div>

    
    <% unless current_user.blank? %>
        <div class="navbar-end">
            <div class="navbar-item">
                <div class="buttons">       
                     
                    <%= link_to 'Cerrar Sesión', destroy_user_session_path, method: :delete, class:"button is-danger" %>
                 
                </div>
            </div>
        </div>
    <% else %>
        <div class="navbar-end">
            <div class="navbar-item">
                <div class="buttons">
                    
                <%= link_to 'Inicia Sesión', new_user_session_path, class:"button is-link" %>
                <%= link_to 'Registrate', new_user_registration_path, class:"button is-light"  %>
    
                </div>
            </div>
        </div>
    <% end %>

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App3</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'  %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    
    <div>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>